name: iOS CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Xcode 15.0.1
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version
      shell: bash

    - name: Set up Git
      run: |
        git config --global user.email "hasnaintechmero@gmail.com"
        git config --global user.name "HasnainTechmero"
        git checkout main
      env:
        GIT_AUTH_TOKEN: ${{ secrets.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 }}

    - name: Update Version and Build Number
      run: |
       # Extract the current version from the Info.plist file
        current_version=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" /Users/techbaroda/Projects/GithubActionsDemo_App/GithubActionsDemo/GithubActionsDemo.xcodeproj/Info.plist)

        # Increment the version number (adjust this based on your versioning scheme)
        new_version=$(echo $current_version | awk -F. '{$NF+=1; OFS="."} 1')

        # Update the Info.plist with the new version
        /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $new_version" /Users/techbaroda/Projects/GithubActionsDemo_App/GithubActionsDemo/GithubActionsDemo.xcodeproj/Info.plist

        # Commit the changes and push to the repository
        git add /Users/techbaroda/Projects/GithubActionsDemo_App/GithubActionsDemo/GithubActionsDemo.xcodeproj/Info.plist
        git commit -m "Bump version to $new_version and build number to $new_build_number"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.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 }}
        
    #- name: Build and Run
    #  run: |
     #   xcodebuild -project /Users/techbaroda/Projects/GithubActionsDemo_App/GithubActionsDemo/GithubActionsDemo.xcodeproj -scheme GithubActionsDemoYourScheme -destination "platform=iOS Simulator,OS=16.0,name=iPhone 13" clean build test
     # working-directory: /Users/techbaroda/Projects/GithubActionsDemo_App/GithubActionsDemo/
      
    
   # - name: Deploy
      #uses: actions/setup-xcode@main
      # Add your deployment steps here, e.g., uploading to App Store Connect or TestFlight
